name: Documentation

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Generate doc
        run: |
          cargo doc --verbose
          echo '<meta http-equiv="refresh" content=0;url="./net_adds/index.html">' > ./target/doc/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
